services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_SID: ORCL
      ORACLE_PDB: PDB1
      ORACLE_PWD: YourPassword
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "tnsping", "ORCL"]
      interval: 30s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  spring-app:
    build:
      context: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/PDB1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.Oracle12cDialect
    restart: unless-stopped

volumes:
  oracle-data:
